mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.example.demo.mybatis.entity
server:
    port: 8080
    servlet:
        context-path: /es-api
spring:
    application:
        name: es-api
    datasource:
        data: classpath:data.sql
        driver-class-name: org.h2.Driver
        password: ''
        schema: classpath:schema.sql
        url: jdbc:h2:file:~/test
        username: san
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
